# Generated by Django 5.1.4 on 2024-12-31 07:01

import app.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='audio_record',
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='sent_to_openai',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OpenAIRequestLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=app.utils.utils.get_char_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_data', models.TextField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('audio_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_requests', to='app.audiorecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='openai_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='app.openairequestlog'),
            preserve_default=False,
        ),
    ]
